version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test_db
    stdin_open: true
    tty: true

  backend:
    build: ./auto-docs-archiver-back
    ports:
      - "8000:8000"
    depends_on:
      - db
